version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:3306
    volumes:
      - ./data/:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  wefit-backend:
    container_name: wefit-backend
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - .:/src/api
    command: 'npm run start:dev'
